/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5.1/userguide/building_java_projects.html
 */

import java.io.File
import java.io.FileInputStream
import java.io.InputStreamReader
import java.util.Properties

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("com.gradle.test.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register("testLocalProp") {
    // Fetch from local.properties
    val localWarningsAsErrors = gradleLocalProperties(rootDir).getProperty("warningsAsErrors")?.toBoolean()
    // Fetch from Gradle properties
    val warningsAsErrors: String? by project
    // Prefer local.properties over gradle.properties, or default to false when both are null
    val finalWarningsAsErrors = localWarningsAsErrors ?: warningsAsErrors.toBoolean()
    println("finalWarningsAsErrors: $finalWarningsAsErrors")
}

fun gradleLocalProperties(projectRootDir : File) : java.util.Properties {
    val properties = Properties()
    val localProperties = File(projectRootDir, "local.properties")
    if (localProperties.isFile) {
        InputStreamReader(FileInputStream(localProperties), Charsets.UTF_8).use { reader ->
            properties.load(reader)
        }
    } else {
        println("Gradle local properties file not found at $localProperties")
    }
    return properties
}
